### ISSUE TITLE
Sprint for v0.5.5 - Public repo

### ISSUE THREAD

**Issue by etsardou** [rapp-project/rapp-platform#149]
Bugs
  - [x] Close #167 [thanos]
  - [x] Close remaining bugs in github after merging with master

Tutorials
  - [x] What is the RAPP platform? Why is it useful?
  - [x] How to create a new rapp-platform ROS node?
  - [x] How can I contribute?
  - [x] How can I set up the rapp platform in my PC?
  - [x] How do I launch the RAPP Platform
  - [x] How can I see that everything is working properly? (testing + rapp health page)
  - [x] I have set it up and everything is working. How can I use it?
  - [x] I do not want to install RAPP Platform. Is there an easier way to use it?
  - [x] I do not even want to try the easier way. Do you have something up and running to test?
  - [x] How to create a HOP service for a ROS service?
  - [x] How to write the API for a HOP service?
  - [x] How to implement an integration test?
  - [x] How to call the HOP service I created?

Documentation
  - [x] Create Doxygen script for main code
  - [x] Create Doxygen script for tests (per package)
  - [x] Create documentation script for HOP services
  - [x] Create documentation script for wiki pages
  - [x] Make JS documentation visually similar to the other docs
  - [x] Duplicate all README.md to the corresponding pages in wiki. The description should exist both in each package AND in wiki (as automated documentation will be produced)
  - [x] Update README in root folder + add rapp platform webpage there

RAPP API
  - [x] Fix link [here](https://github.com/rapp-project/rapp-api/blob/master/README.md) [Kostas]
  - [x] Fix typo ```ontology_is_supsuperclass_of``` - should be subsuperclass
  - [x] Check documentation in rapp-api
  - [x] Add API documentation in documentation scripts and html page
  - [x] Write tutorials for rapp-api (if not existent yet)

Deployment
  - [x] Update RAPP Platform webpage with into
  - [x] Produce ova
  - [x] Upload ova where?
  - [x] Produce script for updating the platform in already setup environments - Kostas
  - [x] Create Travis script and check it works
  - [x] Create script for updating the online documentation
  - [x] Update online documentation with Travis
  - [x] Add gitter

Aftermath
  - [x] Clean up branches
  - [x] Try once more the clean installation
  - [x] Check once more all the wiki pages
  - [x] Check once more the documentation

**Comment by klpanagi** [comment]
Completed task for Python Rapp API: https://github.com/rapp-project/rapp-api/pull/5
