### ISSUE TITLE
Investigated sentences subtraction while  testing the CognitiveExercises

### ISSUE THREAD

**Issue by klpanagi** [rapp-project/rapp-platform#169]
The source of this issue does not seem to be clear. Might be on of:
* text_to_speech module.
* invalid characters in sentences included in cognitive_exercises texts.
* data-loose on speech file transfers??!!

**Comment by etsardou** [comment]
Happens only for Greek ans seems to cut off ~10-20% of the text at the end. English version works fine. We need to find an alternative.
