### ISSUE TITLE
Edit cognitive exercise readme/wiki

### ISSUE THREAD

**Issue by athallas** [rapp-project/rapp-platform#173]
Edit content of wiki and readme file.

example:
[Audio processing README](https://github.com/rapp-project/rapp-platform/blob/documentation/rapp_audio_processing/README.md)
[Audio processing Wiki Page](https://github.com/rapp-project/rapp-platform/wiki/RAPP-Audio-Processing)

**Make sure to add the wiki link at the top of the README file**

**Comment by etsardou** [comment]
@thanoski has this finished?

**Comment by thanoski** [comment]
yes
