### ISSUE TITLE
Retrieve cognitive game information

### ISSUE THREAD

**Issue by etsardou** [rapp-project/rapp-platform#175]
Create:
- [x] ROS service to get score per test category for a user
- [x] The corresponding HOP service
- [x] ROS service to get the history of scores for a user
- [x] The corresponding HOP service
- [x] HOP service with HTML front-end to  visualize the user's tests history

**Comment by thanoski** [comment]
Completed in 3c60a2317e6bbca14c6ebd2d6492ec1fa8a979cc

**Comment by etsardou** [comment]
Are HOP services finished? If yes, please check them above.

**Comment by akintsakis** [comment]
yes HOP services are finished + tested
