### ISSUE TITLE
CI - Travis issues

### ISSUE THREAD

**Issue by etsardou** [rapp-project/rapp-platform#182]
- [x] Must fail when Unit & functional fail - check ROS
- [x] Must fail when Integration tests fail - when something fails, return error code
- [x] Push documentation only when the push is on master
- [x] Check the ```Not building database; man-db/auto-update is not 'true'.``` Travis error
- [x] Check the ```The directory '/home/travis/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.``` error
- [x] Check the ```Policy CMP0046 is not set: Error on non-existent dependency in add_dependencies``` warning
- [x] Suppress hop & bigloo compilation warnings
- [x] Add more echo messages in scripts
- [x] Functional tests for google?
- [x] Add delay in integration tests (15-20 secs)
- [x] Investigate ```mv: cannot move ‘/home/travis/rapp_platform_files/documentation/platform_tests’ to ‘./platform_tests’: Directory not empty``` error in documentation creation
- [ ] Check JSDoc
- [ ] Add more tests (threaded etc)

**Comment by athallas** [comment]
>Policy CMP0046 is not set: Error on non-existent dependency in add_dependencies

This is a catkin [issue](https://github.com/ros/catkin/issues/761)

**Comment by athallas** [comment]
>The directory '/home/travis/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.

Not supported in the current version. [link](https://docs.travis-ci.com/user/caching/)

**Comment by etsardou** [comment]
Closing this. Made the remaining two new issues.
