### ISSUE TITLE
Noise profile files unavailable in clean install tests

### ISSUE THREAD

**Issue by athallas** [rapp-project/rapp-platform#184]
Noise profile files should be present for speech detection tests without running rapp_audio_processing unit/functional tests.

Should also remove corresponding line in [travis.yml](https://github.com/rapp-project/rapp-platform/blob/master/.travis.yml):
`catkin_make run_tests_rapp_audio_processing -j1`

**Comment by etsardou** [comment]
d8d94936c90e15719911ece1e30fefee565af095
