### ISSUE TITLE
Create script for new user creation

### ISSUE THREAD

**Issue by etsardou** [rapp-project/rapp-platform#188]
DB & HOP
- Add it in scripts/setup
- Update the corresponding wiki pages (of scripts)

**Comment by klpanagi** [comment]
Created in devel_scripts/create_rapp_user branch:
88cc6a580c70edc27515f8a7abc049b7658d15af

**Comment by etsardou** [comment]
246dd6aec3ecf354b1aa7d9657e14b1b463b3fd2
