### ISSUE TITLE
Scripts' individual READMEs are obsolete.

### ISSUE THREAD

**Issue by athallas** [rapp-project/rapp-platform#192]
READMEs in [setup](https://github.com/rapp-project/rapp-platform/tree/master/rapp_scripts/setup) and [deploy](https://github.com/rapp-project/rapp-platform/tree/master/rapp_scripts/deploy) are not up-to-date. They should be updated or probably deleted (@etsardou ?) since they are included in the main [rapp_scripts README](https://github.com/rapp-project/rapp-platform/tree/master/rapp_scripts/README.md). The main [rapp_scripts README](https://github.com/rapp-project/rapp-platform/tree/master/rapp_scripts/README.md) must also be updated:

- [ ] Remove `step 0 - Github Installation` subsection from setup section (The user could just download the repository or the setup scripts).
- [ ] In the deploy section `./deploy_hop_services` must be corrected.
- [ ] In the deploy section the screen reference should be made optional and different ttys for the two deploy scripts should be presented as the default option.

**Comment by etsardou** [comment]
Indeed, they should be updated according to the wiki pages.

**Comment by etsardou** [comment]
5cffe8328347453ef08031457ea8c466f186544f
