### ISSUE TITLE
Integrate creation of default rapp user on clean_install

### ISSUE THREAD

**Issue by klpanagi** [rapp-project/rapp-platform#198]
A script exists for rapp_user_creation: [create_rapp_user.sh](https://github.com/rapp-project/rapp-platform/blob/master/rapp_scripts/devel/create_rapp_user.sh)

Use this script on clean_install to create the default rapp user.

Also:
- Delete the "**rapp**" user from [RappPlatformMySqlDbSchema](https://github.com/rapp-project/rapp-platform/blob/master/rapp_scripts/setup/RappPlatformMySqlDbSchema.sql).
- Delete the "**rapp**" user from hop-authenticated-users, [here](https://github.com/rapp-project/rapp-platform/blob/master/rapp_web_services/config/hop/hoprc.js).

**Comment by athallas** [comment]
@klpanagi What's the status? Should this be removed due to the new database?

**Comment by klpanagi** [comment]
This is related to HttpBasicAuthentication previously used to authenticate users for accessing Platform's resources.
We currently use token-based application authentication mechanisms for these purposes so this issue os considered to be deprecated and should be closed.
