### ISSUE TITLE
Travis CI: Do not push in gh-pages if the pull request concerns the master

### ISSUE THREAD

**Issue by etsardou** [rapp-project/rapp-platform#204]

**Comment by etsardou** [comment]
Fixed in 6dfaf853c93cd35fc9afb193ea50e3ccd601afca . Still needs to be checked when pushed to master.

**Comment by athallas** [comment]
Check Travis error ([build link](https://travis-ci.org/rapp-project/rapp-platform/builds/97246865#L3027)): 
```
/home/travis/build.sh: line 45: test: too many arguments
```

**Comment by etsardou** [comment]
4be9e0baf9da1605f73ef87b53ef2479a80e191b

https://travis-ci.org/rapp-project/rapp-platform/builds/97400292

Again we must recheck with master and with a pull request.
