### ISSUE TITLE
User's email credentials should not be stored in the platform

### ISSUE THREAD

**Issue by athallas** [rapp-project/rapp-platform#220]
A better/safer solution would be to store the credentials in the agent, i.e. in a conf file accessible only by the calling process (and the root, of course). These will then be sent to the cloud via HOP's encrypted connection.

Database schema should be modified accordingly.

**Comment by etsardou** [comment]
Specifically:
- [ ] Erase tblEmail
- [ ] Erase email_id from tlbUser
- [ ] Keep email column in tblUser for communication purposes
