### ISSUE TITLE
[Cognitive-System]: Scores not in range [0, 100]

### ISSUE THREAD

**Issue by klpanagi** [rapp-project/rapp-platform#227]
Total user's performance score on cognitive exercises should be in range [0, 100].
Though i get a response from cognitive_get_scores service that exceeds this range

```python
{u'error': u'', u'testCategories': [u'ArithmeticCts', u'ReasoningCts', u'AwarenessCts'], u'testScores': [16, 150, 50]}
```

**Comment by akintsakis** [comment]
When recording a new cognitive test performance entry, the score is in range [0,100]. These scores are different, they are cumulative and multipliers are applied based on the score's difficulty level, thus they are not restricted in the [0,100] range.

**Comment by klpanagi** [comment]
So i understand that there does not exist a normalized range for global performance scores.
Is this right?

**Comment by klpanagi** [comment]
Score values should be now normalized in range [0, 100].
Functional tests should be created to evaluate this.
