### ISSUE TITLE
[HOP services]: details of `available_services`

### ISSUE THREAD

**Issue by alexge233** [rapp-project/rapp-platform#232]
The wiki doesn't have any details on the parameters and return types of the `available_services`.
Can you please add the implementation info?

**Comment by klpanagi** [comment]
Thank you for mentioning that @alexge233 
I will update the documents as soon as possible.

**Comment by klpanagi** [comment]
Updated [here](https://github.com/rapp-project/rapp-platform/tree/front_end/refactor/rapp_web_services/services) and [here](http://rapp-project.github.io/rapp-platform/platform_web_services/services/global.html#available_services).
