### ISSUE TITLE
Microsoft CNTK: deep-learning toolkit

### ISSUE THREAD

**Issue by klpanagi** [rapp-project/rapp-platform#236]
Microsoft has released open-source it's deep-learning toolkit:
[Microsoft-CNTK](https://github.com/Microsoft/CNTK)

**Comment by alexge233** [comment]
Will this build on Unix/Linux?
I would prefer usage of JavaScript based related services, which could be easily wrapped around with node.JS:

* [npm dnn](https://www.npmjs.com/package/dnn)
* [conv net js](https://github.com/karpathy/convnetjs)
* [recurrent js](https://github.com/karpathy/recurrentjs)
* [brain js](https://github.com/harthur/brain)
* [synaptic js](https://github.com/cazala/synaptic)

If you have something specific in mind (e.g., object recognition) we would then require GPGU capabilities, and we could use [caffee](https://github.com/rapp-project/caffe) which somebody has forked for rapp.

Using MS code, even on Unix/Linux could be very tricky.

**Comment by etsardou** [comment]
This issue is just for us having it in mind, it's not meant for implementation for now. Concerning the caffe, Thanos is already working on a wrapper (that's why it is forked).
