### ISSUE TITLE
Setup scripts: When cloning external repos checkout specific tag / commit

### ISSUE THREAD

**Issue by etsardou** [rapp-project/rapp-platform#239]

**Comment by athallas** [comment]
Sphinx was forked by rapp-project and a specific branch was created.

**Comment by athallas** [comment]
A fork should probably be created for HOP/Bigloo. Travis is broken again due to tarball inconsistencies.

**Comment by etsardou** [comment]
- [ ] Bigloo (update tar in our server till Github is available)
- [ ] Fork the repos in rosjava.install in RAPP: https://github.com/rapp-project/rapp-platform/blob/devel/rapp_scripts/setup/rosjava.rosinstall

**Comment by etsardou** [comment]
rosjava repos fixed. Bigloo remaining.

**Comment by etsardou** [comment]
Bigloo is here: http://rapp-project.eu/bigloo4.3a.tar.gz until it is uploaded in Github.
