### ISSUE TITLE
Create web services for new nodes  

### ISSUE THREAD

**Issue by athallas** [rapp-project/rapp-platform#249]
- [x] Email
- [x] Weather
- [x] News
- [x] Geolocator

**Comment by klpanagi** [comment]
email_fetch Web Service introduced in 2b1fe0e3061669d057aba83f10b74d43d26af221

**Comment by klpanagi** [comment]
news_explore Web Service introduced in 59c8e8fc9c322a8407afa0bccaa12f280e219761

**Comment by klpanagi** [comment]
geolocator Web Service introduced in f81bd8c27c82fa4ef400b241872f941be6353116

**Comment by klpanagi** [comment]
**Weather Report** web services pushed to [web_services branch](https://github.com/rapp-project/rapp-platform/tree/web_services):
- weather_report_forecast: e530a3d65ebf70794381e1c08fbc2b2fcb8d8b8a
- weather_report_current: 8eaafddf572b16da8e70fa9be1337b1c7dd8bfe5
