### ISSUE TITLE
Cognitive integration tests fail

### ISSUE THREAD

**Issue by athallas** [rapp-project/rapp-platform#253]

**Comment by klpanagi** [comment]
This is due to the updates in Python RAPP-API.
I can either patch the devel branch of python-rapp-api or wait for web_services branch to merge with devel branch.

**Comment by etsardou** [comment]
Status?

**Comment by klpanagi** [comment]
Fixes merged in devel.
[TravisCI devel build Passed](https://travis-ci.org/rapp-project/rapp-platform/builds/114215023)
