### ISSUE TITLE
Can not build HOP independently

### ISSUE THREAD

**Issue by athallas** [rapp-project/rapp-platform#258]
Missing several packages. Probably `autoconf`.

if this is not enough try also `autotools-dev` or `automake`

**Comment by athallas** [comment]
Also `libpcre3-dev`

**Comment by klpanagi** [comment]
Trace - Required:
 - autotools-dev
 - libpcre3-dev
 - libssl-dev
 - libmpg123-dev
 - libsqlite3-dev
 - libflac-dev
 - libavahi-client-dev
 - libgmp-dev

The **phidget** api bigloo support is not required as we do not support phidget hardware...

**Comment by athallas** [comment]
#280
