### ISSUE TITLE
suggestion: ros_caffee

### ISSUE THREAD

**Issue by alexge233** [rapp-project/rapp-platform#263]
Just a suggestion, I was browsing around for caffe cpp lib wrappers, and found this [ros caffe wrapper](https://github.com/tzutalin/ros_caffe) which comes with a YouTube [demo](https://www.youtube.com/watch?v=T8ZnnTpriC0).

Hope it helps!

**Comment by etsardou** [comment]
@akintsakis did you use this one or wrapped it with another method?

**Comment by akintsakis** [comment]
I used the default python caffe API within my ros node. I will check this one out in case it has any features we are interested in.

**Comment by etsardou** [comment]
Closing this. @akintsakis will check it. Thanks for the info!
