### ISSUE TITLE
Fix Bigloo issue in master branch

### ISSUE THREAD

**Issue by etsardou** [rapp-project/rapp-platform#264]

**Comment by klpanagi** [comment]
Success build of bigloo and hop [CI-build](https://travis-ci.org/rapp-project/rapp-platform/builds/116406082#L3058)

**Comment by athallas** [comment]
@klpanagi @etsardou status? should we close this?

**Comment by etsardou** [comment]
Indeed this should be closed but master still fails due to sphinx. Please open a related issue.
