### ISSUE TITLE
[rapp_path_planning]: Suppress output to stdout

### ISSUE THREAD

**Issue by klpanagi** [rapp-project/rapp-platform#271]
@dudekw  Please remove [outputs to stdout](https://travis-ci.org/rapp-project/rapp-platform/builds/116705261#L3576) from rapp_path_planning node .
If you want to keep logging on the node behavior, please redirect stdout to a log file.

**Comment by klpanagi** [comment]
@dudekw...  Status?

**Comment by etsardou** [comment]
@dudekw any updates?
