### ISSUE TITLE
suggestion: TTS move from mbrola to MaryTTS

### ISSUE THREAD

**Issue by alexge233** [rapp-project/rapp-platform#272]
Mbrola sucks, I'm sorry to be so blunt but it just sucks big time.

Searching for open-source TTS I found a free one [called Mary TTS](http://mary.dfki.de/download/index.html).

It is very recent (December 2015) appears to be actively maintained, and has proper audio output, which you can test for your-self [here](http://mary.dfki.de:59125/), and uses GNU v3.

The only downside I can think of is that its written in Java, so we'd have to use ROS-Java in order to use it.

**Comment by etsardou** [comment]
We had seen Mary TTS in the past but it has not Greek support, so that;s why we did not choose it. We will investigate the addition of this functionalitity while keeping Mbrola as well.
