### ISSUE TITLE
Fix/Update scripts.

### ISSUE THREAD

**Issue by athallas** [rapp-project/rapp-platform#280]
- [x] Move scripts to another repository
  - [x] Update travis scripts accordingly
  - [x] Verify documentation scripts
- [x] Update README
- [x] Fix 6_platform (duplicate travis checks)
- [x] Fix caffee scripts (for both functionality and script output)
- [x] Remove obsolete devel scripts
- [x] Should consider proper deploy configuration
  - Now extra information needed for testing and travis ci is installed which in deployment should be removed. Add initialization script and add documentation about the "clean" setup.
- [x] #273
- [x] #275
- [x] #239
- [x] #258

**Comment by athallas** [comment]
Includes #273 #275 #239

**Comment by etsardou** [comment]
About moving the scripts to the other repo:
- Move deploy, documentation, setup
- Delete continuous_integration
- Add backup and devel scripts to a new folder named utilities

**Comment by athallas** [comment]
moved to scripts repository
