### ISSUE TITLE
Add more integration tests

### ISSUE THREAD

**Issue by etsardou** [rapp-project/rapp-platform#285]

**Comment by etsardou** [comment]
@klpanagi @athallas give a description / guideline on what integration tests we want

**Comment by klpanagi** [comment]
**Integration tests**:  Test communication paths between different parts of the system done by the test to show that all modules/components (independent or cooperative) work correctly together.

**Communication paths between major components of the RAPP ecosystem**:
- Client (rapp-platform-api) ---> WebServices
- WebServices ---> ROS-Services
- ROS-Services ---> WebServices
- WebServices ---> Client (rapp-platform-api)

**Expected failures should be tested too**:
- Sending/Receiving invalid messages:
  * Attribute Errors
  * Type Errors
  * Value Errors
- Service existence
- Authentication failures
- Server Internal Errors
- Client Errors
- Server HTTP Errors (4xx)
- Client HTTP Errors (5xx)
