### ISSUE TITLE
Documentation: Add step-by-step tutorials

### ISSUE THREAD

**Issue by etsardou** [rapp-project/rapp-platform#288]
- How to write RApps
- How to add a functionality in the platform
- How to write a cloud agent (how to create the image and how to test it via calls)

**Comment by etsardou** [comment]
Remaining for v0.6: @klpanagi  In-robot application for NAO in Python: Create a cognitive game (hard)

**Comment by etsardou** [comment]
@klpanagi ?

**Comment by klpanagi** [comment]
The CognitiveGames RApp was initially implemented with no use of the **rapp-robot-api**, thus we need to refactor it to use the **nao** implementation of the rapp-robot-api before providing a step-by-step tutorial
