### ISSUE TITLE
Path planning: Fix warning during compilation

### ISSUE THREAD

**Issue by etsardou** [rapp-project/rapp-platform#294]
https://travis-ci.org/rapp-project/rapp-platform/builds/123061310#L1367

**Comment by dudekw** [comment]
Unfortunately, this warning is caused by the external ROS package - **costmap_2d**. To resolve this bug I would need to change the package source code and join it to the rapp_path_planning package. Should I do it?

**Comment by etsardou** [comment]
If it is from an external package, there is no need to resolve it by forking. I'm closing this.
