### ISSUE TITLE
Update create_rapp_user.sh script

### ISSUE THREAD

**Issue by etsardou** [rapp-project/rapp-platform#299]
Add authentication credentials

**Comment by klpanagi** [comment]
The [create_rapp_user.sh](https://github.com/rapp-project/rapp-platform/blob/devel/rapp_scripts/devel/create_rapp_user.sh) script is deprecated as integration of the RAPP authentication manager changed the way of registering new users
Web Services exist for creating rapp users:

- register_user_from_store
- register_user_from_platform

**Comment by etsardou** [comment]
Then maybe call them from this script in order to be convenient for a non-ros user to easily and quickly create a user
