### ISSUE TITLE
Remove face recognition from devel branch

### ISSUE THREAD

**Issue by etsardou** [rapp-project/rapp-platform#308]
@jfigat please remove the face detection node from the ```devel``` branch as this is meant to be stable, pre-release branch. Create a new branch from devel, add the functionalities, follow the following guidelines:
- https://github.com/rapp-project/rapp-platform/wiki/How-to-create-a-new-RAPP-Platform-ROS-node%3F
- https://github.com/rapp-project/rapp-platform/wiki/How-to-create-a-HOP-service-for-a-ROS-service%3F
- https://github.com/rapp-project/rapp-platform/wiki/How-to-write-the-API-for-a-HOP-service%3F

and when its ready make a pull request to merge your branch to the ```devel``` branch.

@maciek-slon

**Comment by athallas** [comment]
Face recognition has been removed from `devel` branch and can be found in `face_recognition` branch
