### ISSUE TITLE
New users without language cause cognitivfe tests to fail.

### ISSUE THREAD

**Issue by athallas** [rapp-project/rapp-platform#321]
- [ ] Update db schema with default value and change field to `NOT NULL`

@akintsakis Shouldn't there be tests regarding this issue?

**Comment by akintsakis** [comment]
The error is successfully caught, but the error message was empty. It was addressed in d4852bb536f680a350dd72fc202d92a421f9ccd2

**Comment by etsardou** [comment]
Is this ready to be closed?

**Comment by etsardou** [comment]
@akintsakis ?

**Comment by athallas** [comment]
[Scripts issue](https://github.com/rapp-project/rapp-platform-scripts/issues/18)

**Comment by athallas** [comment]
Language can be NULL, but if user is expected to use cognitive tests should specify a language at creation.
