### ISSUE TITLE
Deployed hop doesn't provide useful information

### ISSUE THREAD

**Issue by athallas** [rapp-project/rapp-platform#338]
#### Connection closed
First, it should stop spamming when connection is lost. It floods the output with:

```
Connection to rosbridge closed
Connecting bridge, {host: localhost, port: 9090}
[Rosbridge]: Rosbridge Websocket interface is broken.  [ws://localhost:9090]
Connecting bridge, {host: localhost, port: 9090}
[Rosbridge]: Rosbridge Websocket interface is broken.  [ws://localhost:9090]
Connecting bridge, {host: localhost, port: 9090}
[Rosbridge]: Rosbridge Websocket interface is broken.  [ws://localhost:9090]
```
There should probably be **only one** error per lost connection on the first occurrence and it should provide information about the broken interface, i.e. interface broken [email/fetch_email] or something like that.

#### Established connection
Secondly and on the same principle, when a connection is established it should provide information about the restored connection, i.e. connection established, service "foo/bar" or smthing. Currently the output provides no useful information:
```
Connecting bridge, {host: localhost, port: 9090}
Connection to rosbridge established
Connecting bridge, {host: localhost, port: 9090}
Connecting bridge, {host: localhost, port: 9090}
Connection to rosbridge established
Connection to rosbridge established
Connecting bridge, {host: localhost, port: 9090}
Connection to rosbridge established
Connection to rosbridge established
Connection to rosbridge established
Connection to rosbridge established
Connection to rosbridge established
```

**Comment by klpanagi** [comment]
The output to stdout is not coming from the web-services implementation, but from the **ROS websocket client** implementation. Each Web Service initiates a single connection to **ROS websocket server**.

> First, it should stop spamming when connection is lost

ROS websocket clients are trying to reconnect to ROS websocket server, with a timeout, when connection is lost. So if 29 Web Services are trying to connect to ROS, while ROS websocket server is down, you will get an output of 29 messages per timeout value (currently 2 seconds)

> There should probably be only one error per lost connection on the first occurrence and it should provide information about the broken interface, i.e. interface broken [email/fetch_email] or something like that

ROS websocket client implementation does not have knowledge of the Web Service it connects to ROS so providing that kind of information cannot be done.

> Secondly and on the same principle, when a connection is established it should provide information about the restored connection, i.e. connection established, service "foo/bar" or smthing. Currently the output provides no useful information:

Same on this one.


Maybe we can provide an updated version of the ROS webscocket client implementation, on a later release, to integrate the suggested features.


Thank you @athallas
