### ISSUE TITLE
Release v0.6

### ISSUE THREAD

**Issue by athallas** [rapp-project/rapp-platform#340]
- [x] Create .ova file [check](https://github.com/rapp-project/rapp-platform/wiki/I-do-not-want-to-install-RAPP-Platform.-Is-there-an-easier-way-to-use-it%3F)
- [x] Deploy platform on server
- [x] Deploy platform on server on power-up
- [x] ROS News announcement
- [x] Check script generated documentation
- [x] https://github.com/rapp-project/rapp-platform/issues/345

**Comment by etsardou** [comment]
- [ ] @athallas  check https://github.com/rapp-project/rapp-platform/wiki/RAPP-Application-Authentication
- [ ] @akintsakis check https://github.com/rapp-project/rapp-platform/wiki/RAPP-Cognitive-Exercise for the new services
- [ ] @akintsakis check https://github.com/rapp-project/rapp-platform/wiki/RAPP-MySQL-wrapper
- [ ] Erroneous link in README of https://github.com/rapp-project/rapp-platform/tree/devel/rapp_text_to_speech_espeak

**Comment by etsardou** [comment]
@klpanagi @akintsakis Status of the check list?

**Comment by etsardou** [comment]
- [x] Release rapp-platform
- [x] Release rapp-api
- [x] Release rapp-robot-api
- [x] Release rapp-platform-scripts
- [x] Release rapp-resources
- [x] Release rapps-nao
- [x] Release knowrob [rapp]

**Comment by klpanagi** [comment]
Need to updade testing-tools related documentation due to the latest changes;

**Comment by etsardou** [comment]
@akintsakis Update [this](https://github.com/rapp-project/rapp-platform/wiki/RAPP-Cognitive-Exercise) with the latest services to proceed with the release.
