### ISSUE TITLE
Error in weather_current_report documentation

### ISSUE THREAD

**Issue by MariaRamos89** [rapp-project/rapp-platform#349]
Hi,

I'm trying to test the `weather_report_current` class and there is no param "error" in json response.
To confirm that I looked for that parameter and the value was nullDate: 1473251165.

In fact, it appears here:

```
{
    date: '', temperature: '', weather_description: '', humidity: '', visibility: '',
    pressure: '', wind_speed: '', wind_temperature: '', wind_direction: '', error: ''
}
```

And not in the description.

Thanks in advance.

**Comment by athallas** [comment]
It is not clear what the problem is. Pls formulate the issue description better.

**Comment by MariaRamos89** [comment]
Sorry for that.

The issue is that in the parameters of the json response documentation appears `date`, `temperature`, ... and `error`, but there is no error when I take the response from the server.

**Comment by lpenteri** [comment]
Indeed no error parameter returned, while the documentation [here](https://github.com/rapp-project/rapp-platform/tree/master/rapp_web_services/services#weather-report-current) says there would be.

**Comment by klpanagi** [comment]
https://github.com/rapp-project/rapp-platform/blob/integration_tests/rapp_testing_tools/scripts/default_tests/exclude/weather_report.py#L38

Response body structure seems just fine to me.

**Comment by MariaRamos89** [comment]
In that file it seems right, but this is the json that I'm receiving:

```
JSON: {"date":"1478624956","temperature":"69.16","weather_description":"Clear","humidity":"0.45","visibility":"10","pressure":"1026.47","wind_speed":"3.48","wind_temperature":"","wind_direction":""}
```

Parameter `error` doesn't appear.

**Comment by klpanagi** [comment]
You are right Maria, i just found the source of this bug!
It seems that the response body is not crafted properly. I am going to prepare a patch for this

Thank you and sorry for any inconvenience caused.

**Comment by klpanagi** [comment]
Hi @MariaRamos89 ,

Did you test service responses on branch [fix_issue_349](https://github.com/rapp-project/rapp-platform/tree/fix_issue_349)??

**Comment by MariaRamos89** [comment]
Fixed!

Sorry for the lateness
