### ISSUE TITLE
Email_fetch is not working

### ISSUE THREAD

**Issue by MariaRamos89** [rapp-project/rapp-platform#351]
Hi,

I've implemented email_fetch class in C++ API and the response from the server was 

```
{"emails" : [], "error": ""}
```

I don't know why is returned this when I know that I have some mails in the account.
I tried changing status_email, dates, etc. but it didn't work.

Thanks in advances

**Comment by klpanagi** [comment]
Check on the parameters of [this](https://github.com/rapp-project/rapp-platform/blob/master/rapp_testing_tools/scripts/default_tests/exclude/email_fetch.py#L35) integration test.

**Comment by etsardou** [comment]
Is this resolved? Any status updates?

**Comment by MariaRamos89** [comment]
Now it's working, thanks
