### ISSUE TITLE
Platform deployed in rapp.ee.auth.gr fails

### ISSUE THREAD

**Issue by lpenteri** [rapp-project/rapp-platform#356]
It returns 500 error code.

**Comment by etsardou** [comment]
Try this tutorial: https://github.com/rapp-project/rapp-platform/wiki/I-do-not-even-want-to-try-the-easier-way.-Do-you-have-something-up-and-running-to-test%3F

**Comment by lpenteri** [comment]
I know I do valid POST requests to the web services because the same requests were working on Thursday. The examples utilizing curl in the tutorial return "Server Error" as well..

**Comment by etsardou** [comment]
It seems to be up.. I restarted it, can you try again?

PS. are you using the correct authentication?

**Comment by lpenteri** [comment]
Now it works :)
