### ISSUE TITLE
Weather service HTTP 500 Error

### ISSUE THREAD

**Issue by MariaRamos89** [rapp-project/rapp-platform#357]
Hi,

When I put `yweather` as weather reporter to call the service  `weather_report_current` or `weather_report_forecast`, the platform return 
```
HTTP/1.1 500  Internal Server Error
```

Could you help me?

**Comment by klpanagi** [comment]
[Yweather support has discontinued](https://github.com/tsroten/yweather#yweather)

Please use the default weather reporter (leave that field empty) to always ensure proper execution.
Though, thanks for the comment. We shall update the documentation and mention this properly

**Comment by MariaRamos89** [comment]
Thank you very much :)
