### ISSUE TITLE
Object_recognition_find_object not return a correct JSON

### ISSUE THREAD

**Issue by MariaRamos89** [rapp-project/rapp-platform#358]
Hi,

In all the previous classes implemented when you take a point from json, the point values are an `x` ,`y` and `z`. But in this case there are only `x` and `y`.

Could you fix it, please?

Thanks in advance

**Comment by maciek-slon** [comment]
There are only `x` and `y` because objects are localized in image space in pixels, not in 3D space. I assume that the problem is with the JSON produced by the web service. I will add additional field for `z`.

**Comment by maciek-slon** [comment]
Fixed :)
