### ISSUE TITLE
The new wut services related to object detection ask for a parameter 'user'

### ISSUE THREAD

**Issue by lpenteri** [rapp-project/rapp-platform#359]
Wasn't this parameter removed from the requests of all services and it was supposed to be retrieved internally in the platform after a login call and the authentication of every request would be done through the token?

**Comment by klpanagi** [comment]
Hello @lpenteri ,

what do you mean "asks" for parameter `user`? From where did you retrieve this information?
Look [here](https://github.com/rapp-project/rapp-platform/blob/devel/rapp_web_services/services/object_detection_clear_models/svc.js#L48). The username is retrieved from the authentication server after validating the `token`.

`client_req` objects are deprecated and are no longer used..

So this is not a problem as the `user` parameter is not used...

@maciek-slon  we also have to update the WebServices list and documentation [here](https://github.com/rapp-project/rapp-platform/tree/devel/rapp_web_services/services#rapp-platform-web-services) to include the **object_detection** related services

**Comment by maciek-slon** [comment]
@klpanagi can I push directly to devel after README change? Or should we do a whole round of branch/pull request/merge? ;-)

**Comment by lpenteri** [comment]
Hi @klpanagi ,

Yes that's why I thought I have to send it, because I saw it in the client_req objects.
Ok then it's not a problem I will not send it. :)

**Comment by klpanagi** [comment]
@maciek-slon create a new branch, having `devel` as parent and push changes there :)

**Comment by maciek-slon** [comment]
OK. See #360
